### ISSUE TITLE
Update README.nl.txt

### ISSUE THREAD

**Issue by runely** [runely/jslogic-homey#10]
@liams239 
I have updated [README.txt](https://github.com/runely/jslogic-homey/blob/dev/README.txt) with some more info. Would you be kind to update [README.nl.txt](https://github.com/runely/jslogic-homey/blob/dev/README.nl.txt) with the same info in Dutch?

Thanks!

**Comment by liams239** [comment]
No problem. Translated readme.nl.txt to new readme. See pull request: #11
