### ISSUE TITLE
Translation checks

### ISSUE THREAD

**Issue by runely** [runely/jslogic-homey#14]
Hi @liams239 

I have added one new condition and and one new action. Would you please check the dutch translation?

[Condition - Random (true|false)](https://github.com/runely/jslogic-homey/blob/dev/.homeycompose/flow/conditions/is_random_true_false.json)
[Action - Get formatted date](https://github.com/runely/jslogic-homey/blob/dev/.homeycompose/flow/actions/get_formatted_date.json)
[Dutch locale](https://github.com/runely/jslogic-homey/blob/dev/locales/nl.json)
[Dutch readme](https://github.com/runely/jslogic-homey/blob/dev/README.nl.txt)

**Comment by liams239** [comment]
Hey, A quick check already and it looks very good. I will check tomorrow to be sure everything is 100% correct.

**Comment by liams239** [comment]
Hi, I have check it. I made 2 little adjustments to the dutch readme and get formatted date files. I have created a pull request for those 2.

**Comment by runely** [comment]
PR's merged
