### ISSUE TITLE
date/time calculation

### ISSUE THREAD

**Issue by ehdegroot** [runely/jslogic-homey#3]
Hey Rune,
you're on a roll :) another potential awesome app.
Will this app get the possibility to calculate with date and time?

example:
if $A is earlier then $B > set boolean
$B - $A = $C

etc

**Comment by runely** [comment]
Hi. Thanks for the feedback 😉

It can get that 👍

**Comment by runely** [comment]
Three new conditions coming in the next version:

- **Is Date before Date** : Check if a Date occurs before another Date
- **Is Time before Time** : Check if one Time occurs before another Time
- **Is DateTime before DateTime** : Check if a DateTime occurs before another DateTime

**Comment by ehdegroot** [comment]
it works!!!! :)
awesome and so quick!! thanks you!
