### ISSUE TITLE
Formatted date returns [null] in new flows

### ISSUE THREAD

**Issue by xgbcman** [runely/jslogic-homey#90]
I have old flows that send push messages and timeline messages and it still works. When I create new flows the return is [null]. Formatted value result is still correct in variable list but is not returned to push and timeline from new flows. The problem appeared before the new version 1.4.0.

**Comment by runely** [comment]
Please share a flow where this is happening. I can't reproduce the output *[null]* from the `Get formatted date` action card

**Comment by xgbcman** [comment]
Sorry, I was wrong. I forget to Get formatted date before using the Tag.

**Comment by xgbcman** [comment]
Sorry, I forget to Get before using Tag.

**Comment by runely** [comment]
Yeah, that will produce _[null]_ if the **Get formatted date** action card hasn't been used since app start, or the last value generated by the **Get formatted date** action card if used after app start
